events {
    worker_connections 1024;
}

http {
    upstream products_backend {
        server products-service:5001;
    }

    server {
        listen 5000;
        server_name localhost;

        location /api/products/ {
            proxy_pass http://products_backend/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

